### PR TITLE
Ignore unknown `Category` instead of returning an error

### PR DESCRIPTION
**Pull request by shamilsan**
I encountered a problem when trying to open one MSI package with undocumented `“Number”` category. In my opinion, it is better to ignore unknown categories rather than to return an error.

### CODE REVIEW

**Comment by shamilsan** [comment]
Dear @mdsteele,

What do you think about it?

**Comment by mdsteele** [comment]
Seems reasonable, sorry for the slow reply.  Looks like there were some clippy errors unrelated to your change; if you rebase those should be fixed now, and then we can merge.

**Comment by shamilsan** [comment]
@mdsteele,

Thanks for your reply. I've synced my fork with the upstream, could you please try again?

**Comment by mdsteele** [comment]
Merged, thanks!

**Pull request merged**
